-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.audit_log
(
    id uuid NOT NULL,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid,
    perfil_usuario audit_user_type_enum,
    project_id uuid,
    tipo_accion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    resource_id uuid,
    datos_adicionales jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.business_glossaries
(
    project_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    terms jsonb NOT NULL,
    comments jsonb NOT NULL,
    current_version_number integer NOT NULL DEFAULT 1,
    created_by_user_id uuid NOT NULL,
    updated_by_user_id uuid,
    last_saved_at timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT business_glossaries_pkey PRIMARY KEY (id),
    CONSTRAINT uq_business_glossary_project_artifact UNIQUE (project_id, artifact_id)
);

CREATE TABLE IF NOT EXISTS public.business_glossary_versions
(
    glossary_id uuid NOT NULL,
    version_number integer NOT NULL,
    snapshot jsonb NOT NULL,
    change_summary text COLLATE pg_catalog."default",
    created_by_user_id uuid,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT business_glossary_versions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_business_glossary_version_number UNIQUE (glossary_id, version_number)
);

CREATE TABLE IF NOT EXISTS public.conceptual_attributes
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    entity_id uuid NOT NULL,
    client_id character varying(120) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    data_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_pk boolean NOT NULL DEFAULT false,
    is_fk boolean NOT NULL DEFAULT false,
    is_nullable boolean NOT NULL DEFAULT true,
    description text COLLATE pg_catalog."default",
    fk_entity_client_id character varying(120) COLLATE pg_catalog."default",
    fk_attribute_ref character varying(255) COLLATE pg_catalog."default",
    order_index integer NOT NULL DEFAULT 0,
    CONSTRAINT conceptual_attributes_pkey PRIMARY KEY (id),
    CONSTRAINT uq_conceptual_attributes_entity_client_id UNIQUE (entity_id, client_id)
);

CREATE TABLE IF NOT EXISTS public.conceptual_entities
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    model_id uuid NOT NULL,
    client_id character varying(120) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    position_x double precision NOT NULL DEFAULT 0,
    position_y double precision NOT NULL DEFAULT 0,
    color character varying(20) COLLATE pg_catalog."default",
    order_index integer NOT NULL DEFAULT 0,
    CONSTRAINT conceptual_entities_pkey PRIMARY KEY (id),
    CONSTRAINT uq_conceptual_entities_model_client_id UNIQUE (model_id, client_id)
);

CREATE TABLE IF NOT EXISTS public.conceptual_model_comments
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    model_id uuid NOT NULL,
    target_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    target_client_id character varying(120) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'open'::character varying,
    created_by_user_id uuid NOT NULL,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by_user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by_user_type user_type_enum NOT NULL,
    created_in_version_number integer NOT NULL DEFAULT 1,
    outdated_at timestamp with time zone,
    CONSTRAINT conceptual_model_comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.conceptual_model_versions
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    model_id uuid NOT NULL,
    version_number integer NOT NULL,
    snapshot_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    change_summary text COLLATE pg_catalog."default",
    created_by_user_id uuid NOT NULL,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT conceptual_model_versions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_conceptual_model_versions_model_version UNIQUE (model_id, version_number)
);

CREATE TABLE IF NOT EXISTS public.conceptual_models
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    project_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    phase conceptual_model_phase_enum NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    current_version integer NOT NULL DEFAULT 1,
    created_by_user_id uuid NOT NULL,
    updated_by_user_id uuid,
    last_saved_at timestamp with time zone,
    CONSTRAINT conceptual_models_pkey PRIMARY KEY (id),
    CONSTRAINT uq_conceptual_models_artifact_id UNIQUE (artifact_id)
);

CREATE TABLE IF NOT EXISTS public.conceptual_relations
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    model_id uuid NOT NULL,
    client_id character varying(120) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    source_entity_client_id character varying(120) COLLATE pg_catalog."default" NOT NULL,
    target_entity_client_id character varying(120) COLLATE pg_catalog."default" NOT NULL,
    cardinality character varying(10) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    fk_attribute_client_id character varying(120) COLLATE pg_catalog."default",
    order_index integer NOT NULL DEFAULT 0,
    CONSTRAINT conceptual_relations_pkey PRIMARY KEY (id),
    CONSTRAINT uq_conceptual_relations_model_client_id UNIQUE (model_id, client_id)
);

CREATE TABLE IF NOT EXISTS public.dfd_comments
(
    id uuid NOT NULL,
    model_id uuid NOT NULL,
    target_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    target_client_id character varying(120) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'open'::character varying,
    created_by_user_id uuid,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by_user_name character varying(255) COLLATE pg_catalog."default",
    created_by_user_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    created_in_version_number integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT dfd_comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dfd_models
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    project_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    phase character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    level integer NOT NULL DEFAULT 1,
    nodes jsonb NOT NULL DEFAULT '[]'::jsonb,
    flows jsonb NOT NULL DEFAULT '[]'::jsonb,
    current_version_number integer NOT NULL DEFAULT 1,
    created_by_user_id uuid NOT NULL,
    updated_by_user_id uuid,
    last_saved_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT dfd_models_pkey PRIMARY KEY (id),
    CONSTRAINT uq_dfd_model_project_artifact UNIQUE (project_id, artifact_id)
);

CREATE TABLE IF NOT EXISTS public.dfd_versions
(
    id uuid NOT NULL,
    model_id uuid NOT NULL,
    version_number integer NOT NULL,
    snapshot jsonb NOT NULL,
    change_summary text COLLATE pg_catalog."default",
    created_by_user_id uuid,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT dfd_versions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_dfd_version_model_number UNIQUE (model_id, version_number)
);

CREATE TABLE IF NOT EXISTS public.gap_analysis_report_versions
(
    report_id uuid NOT NULL,
    version_number integer NOT NULL,
    snapshot jsonb NOT NULL,
    change_summary text COLLATE pg_catalog."default",
    created_by_user_id uuid,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT gap_analysis_report_versions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_gap_analysis_report_version_number UNIQUE (report_id, version_number)
);

CREATE TABLE IF NOT EXISTS public.gap_analysis_reports
(
    project_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    executive_summary text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    gaps jsonb NOT NULL,
    total_gaps integer NOT NULL DEFAULT 0,
    critical_gaps integer NOT NULL DEFAULT 0,
    priority_recommendations jsonb NOT NULL,
    target_formats jsonb NOT NULL,
    current_version_number integer NOT NULL DEFAULT 1,
    created_by_user_id uuid NOT NULL,
    updated_by_user_id uuid,
    last_saved_at timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT gap_analysis_reports_pkey PRIMARY KEY (id),
    CONSTRAINT uq_gap_analysis_report_project_artifact UNIQUE (project_id, artifact_id)
);

CREATE TABLE IF NOT EXISTS public.gaps_crud_matrices
(
    project_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    comparisons jsonb NOT NULL,
    current_version_number integer NOT NULL DEFAULT 1,
    created_by_user_id uuid NOT NULL,
    updated_by_user_id uuid,
    last_saved_at timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT gaps_crud_matrices_pkey PRIMARY KEY (id),
    CONSTRAINT uq_gaps_crud_matrix_project_artifact UNIQUE (project_id, artifact_id)
);

CREATE TABLE IF NOT EXISTS public.gaps_crud_matrix_versions
(
    matrix_id uuid NOT NULL,
    version_number integer NOT NULL,
    snapshot jsonb NOT NULL,
    change_summary text COLLATE pg_catalog."default",
    created_by_user_id uuid,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT gaps_crud_matrix_versions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_gaps_crud_matrix_version_number UNIQUE (matrix_id, version_number)
);

CREATE TABLE IF NOT EXISTS public.integration_quality_rules
(
    project_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    technical_summary text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    rules jsonb NOT NULL,
    acceptance_criteria jsonb NOT NULL,
    target_formats jsonb NOT NULL,
    current_version_number integer NOT NULL DEFAULT 1,
    created_by_user_id uuid NOT NULL,
    updated_by_user_id uuid,
    last_saved_at timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT integration_quality_rules_pkey PRIMARY KEY (id),
    CONSTRAINT uq_integration_quality_rules_project_artifact UNIQUE (project_id, artifact_id)
);

CREATE TABLE IF NOT EXISTS public.integration_quality_rules_versions
(
    document_id uuid NOT NULL,
    version_number integer NOT NULL,
    snapshot jsonb NOT NULL,
    change_summary text COLLATE pg_catalog."default",
    created_by_user_id uuid,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT integration_quality_rules_versions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_integration_quality_rules_version_number UNIQUE (document_id, version_number)
);

CREATE TABLE IF NOT EXISTS public.inventory_matrices
(
    project_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    systems jsonb NOT NULL,
    comments jsonb NOT NULL,
    current_version_number integer NOT NULL DEFAULT 1,
    created_by_user_id uuid NOT NULL,
    updated_by_user_id uuid,
    last_saved_at timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT inventory_matrices_pkey PRIMARY KEY (id),
    CONSTRAINT uq_inventory_matrix_project_artifact UNIQUE (project_id, artifact_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_matrix_versions
(
    matrix_id uuid NOT NULL,
    version_number integer NOT NULL,
    snapshot jsonb NOT NULL,
    change_summary text COLLATE pg_catalog."default",
    created_by_user_id uuid,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT inventory_matrix_versions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_inventory_matrix_version_number UNIQUE (matrix_id, version_number)
);

CREATE TABLE IF NOT EXISTS public.invitations
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    invited_user_type invited_user_type_enum NOT NULL,
    status invitation_status_enum NOT NULL DEFAULT 'PENDIENTE'::invitation_status_enum,
    project_id uuid,
    invited_by_user_id uuid NOT NULL,
    target_user_id uuid,
    expires_at timestamp with time zone NOT NULL,
    accepted_at timestamp with time zone,
    CONSTRAINT invitations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logical_data_model_comments
(
    model_id uuid NOT NULL,
    target_type character varying(32) COLLATE pg_catalog."default" NOT NULL,
    target_client_id character varying(120) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    status character varying(32) COLLATE pg_catalog."default" NOT NULL DEFAULT 'open'::character varying,
    created_by_user_id uuid,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by_user_name character varying(255) COLLATE pg_catalog."default",
    created_by_user_type character varying(32) COLLATE pg_catalog."default" NOT NULL,
    created_in_version_number integer NOT NULL DEFAULT 1,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT logical_data_model_comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logical_data_model_versions
(
    model_id uuid NOT NULL,
    version_number integer NOT NULL,
    snapshot jsonb NOT NULL,
    change_summary text COLLATE pg_catalog."default",
    created_by_user_id uuid,
    created_by_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT logical_data_model_versions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_logical_model_version_number UNIQUE (model_id, version_number)
);

CREATE TABLE IF NOT EXISTS public.logical_data_models
(
    project_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    phase character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    tables jsonb NOT NULL DEFAULT '[]'::jsonb,
    sql_ddl text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    notes_markdown text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    comments jsonb NOT NULL DEFAULT '[]'::jsonb,
    versions jsonb NOT NULL DEFAULT '[]'::jsonb,
    current_version character varying(32) COLLATE pg_catalog."default" NOT NULL DEFAULT 'v1.0'::character varying,
    created_by_user_id uuid,
    updated_by_user_id uuid,
    last_saved_at timestamp with time zone NOT NULL DEFAULT now(),
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT logical_data_models_pkey PRIMARY KEY (id),
    CONSTRAINT uq_logical_model_project_artifact UNIQUE (project_id, artifact_id)
);

CREATE TABLE IF NOT EXISTS public.maturity_answers
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    response_id uuid NOT NULL,
    question_id uuid NOT NULL,
    respondent_score integer NOT NULL,
    validated_score integer,
    estado_validacion maturity_answer_validation_status_enum NOT NULL DEFAULT 'PENDIENTE'::maturity_answer_validation_status_enum,
    validation_comments text COLLATE pg_catalog."default",
    evidence_url text COLLATE pg_catalog."default",
    evidence_name text COLLATE pg_catalog."default",
    evidence_type text COLLATE pg_catalog."default",
    evidence_size integer,
    CONSTRAINT maturity_answers_pkey PRIMARY KEY (id),
    CONSTRAINT uq_maturity_answer_response_question UNIQUE (response_id, question_id)
);

CREATE TABLE IF NOT EXISTS public.maturity_dimensions
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    weight numeric(5, 4) NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT maturity_dimensions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.maturity_questionnaires
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    project_id uuid NOT NULL,
    phase character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'AS_IS'::character varying,
    is_closed boolean NOT NULL DEFAULT false,
    access_code character varying(64) COLLATE pg_catalog."default" NOT NULL,
    access_expires_at timestamp with time zone,
    created_by_user_id uuid NOT NULL,
    closed_by_user_id uuid,
    closed_at timestamp with time zone,
    dimension_weights_override jsonb NOT NULL,
    custom_roles_override jsonb NOT NULL,
    score_criteria_override jsonb NOT NULL,
    CONSTRAINT maturity_questionnaires_pkey PRIMARY KEY (id),
    CONSTRAINT uq_maturity_questionnaire_access_code UNIQUE (access_code),
    CONSTRAINT uq_maturity_questionnaire_project_phase UNIQUE (project_id, phase)
);

CREATE TABLE IF NOT EXISTS public.maturity_questions
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    questionnaire_id uuid NOT NULL,
    dimension_id integer NOT NULL,
    subdomain_id integer NOT NULL,
    text text COLLATE pg_catalog."default" NOT NULL,
    applicable_roles jsonb NOT NULL DEFAULT '[]'::jsonb,
    weight numeric(5, 4) NOT NULL DEFAULT 1.0,
    is_active boolean NOT NULL DEFAULT true,
    score_criteria_override jsonb NOT NULL,
    CONSTRAINT maturity_questions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.maturity_responses
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    questionnaire_id uuid NOT NULL,
    respondent_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    respondent_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status maturity_response_status_enum NOT NULL DEFAULT 'active'::maturity_response_status_enum,
    estado_validacion maturity_validation_status_enum NOT NULL DEFAULT 'PENDIENTE'::maturity_validation_status_enum,
    anulation_reason text COLLATE pg_catalog."default",
    anulated_at timestamp with time zone,
    anulated_by_user_id uuid,
    validated_by_user_id uuid,
    validated_at timestamp with time zone,
    validation_comments text COLLATE pg_catalog."default",
    submitted_at timestamp with time zone NOT NULL,
    CONSTRAINT maturity_responses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.maturity_subdomains
(
    id serial NOT NULL,
    dimension_id integer NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    weight numeric(5, 4) NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT maturity_subdomains_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.project_artifact_permissions
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    project_id uuid NOT NULL,
    artifact_id uuid NOT NULL,
    user_id uuid NOT NULL,
    permission_level integer NOT NULL,
    assigned_by_user_id uuid,
    CONSTRAINT project_artifact_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_project_artifact_permission_artifact_user UNIQUE (artifact_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.project_artifacts
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    project_id uuid NOT NULL,
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    block project_artifact_block_enum NOT NULL,
    order_index integer NOT NULL,
    block_order integer NOT NULL,
    status project_artifact_status_enum NOT NULL DEFAULT 'PENDING'::project_artifact_status_enum,
    is_applicable boolean NOT NULL DEFAULT true,
    consultant_approved boolean NOT NULL DEFAULT false,
    company_approved boolean NOT NULL DEFAULT false,
    consultant_approved_at timestamp with time zone,
    company_approved_at timestamp with time zone,
    approved_at timestamp with time zone,
    approved_by_user_id uuid,
    review_cycles integer NOT NULL DEFAULT 0,
    last_rejection_reason text COLLATE pg_catalog."default",
    CONSTRAINT project_artifacts_pkey PRIMARY KEY (id),
    CONSTRAINT uq_project_artifact_project_code UNIQUE (project_id, code)
);

CREATE TABLE IF NOT EXISTS public.project_memberships
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    is_manager boolean NOT NULL DEFAULT false,
    nivel_asis integer,
    nivel_tobe integer,
    nivel_brechas integer,
    assigned_by_user_id uuid,
    project_permission_level integer,
    nivel_roadmap integer,
    CONSTRAINT project_memberships_pkey PRIMARY KEY (id),
    CONSTRAINT uq_project_membership_project_user UNIQUE (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado project_status_enum NOT NULL DEFAULT 'ACTIVO'::project_status_enum,
    manager_user_id uuid NOT NULL,
    client_company_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    client_company_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    estimated_end_date date NOT NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.raci_activities
(
    matrix_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category character varying(100) COLLATE pg_catalog."default" NOT NULL,
    order_index integer NOT NULL,
    notas text COLLATE pg_catalog."default",
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT raci_activities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.raci_assignments
(
    matrix_id uuid NOT NULL,
    activity_id uuid NOT NULL,
    role_id uuid NOT NULL,
    assignment_type raci_assignment_type_enum NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT raci_assignments_pkey PRIMARY KEY (id),
    CONSTRAINT uq_raci_assignment_activity_role UNIQUE (activity_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.raci_comments
(
    matrix_id uuid NOT NULL,
    reference_id uuid,
    reference_type raci_comment_reference_type_enum NOT NULL,
    author_id uuid NOT NULL,
    author_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    author_perfil character varying(255) COLLATE pg_catalog."default" NOT NULL,
    contenido text COLLATE pg_catalog."default" NOT NULL,
    estado character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT raci_comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.raci_matrices
(
    project_id uuid NOT NULL,
    entregable_id uuid,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    status raci_status_enum NOT NULL,
    version_actual character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT raci_matrices_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.raci_roles
(
    matrix_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    area character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    order_index integer NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT raci_roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.raci_version_history
(
    matrix_id uuid NOT NULL,
    version character varying(50) COLLATE pg_catalog."default" NOT NULL,
    autor character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion_cambio text COLLATE pg_catalog."default" NOT NULL,
    total_actividades integer NOT NULL,
    total_roles integer NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT raci_version_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    token_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default",
    tipo_usuario user_type_enum NOT NULL,
    estado user_status_enum NOT NULL DEFAULT 'PENDIENTE'::user_status_enum,
    created_by_user_id uuid,
    deactivated_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT audit_log_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_audit_log_project_id
    ON public.audit_log(project_id);


ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_audit_log_user_id
    ON public.audit_log(user_id);


ALTER TABLE IF EXISTS public.business_glossaries
    ADD CONSTRAINT business_glossaries_artifact_id_fkey FOREIGN KEY (artifact_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.business_glossaries
    ADD CONSTRAINT business_glossaries_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.business_glossaries
    ADD CONSTRAINT business_glossaries_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.business_glossaries
    ADD CONSTRAINT business_glossaries_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.business_glossary_versions
    ADD CONSTRAINT business_glossary_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.business_glossary_versions
    ADD CONSTRAINT business_glossary_versions_glossary_id_fkey FOREIGN KEY (glossary_id)
    REFERENCES public.business_glossaries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.conceptual_attributes
    ADD CONSTRAINT conceptual_attributes_entity_id_fkey FOREIGN KEY (entity_id)
    REFERENCES public.conceptual_entities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_conceptual_attributes_entity_id
    ON public.conceptual_attributes(entity_id);


ALTER TABLE IF EXISTS public.conceptual_entities
    ADD CONSTRAINT conceptual_entities_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.conceptual_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_conceptual_entities_model_id
    ON public.conceptual_entities(model_id);


ALTER TABLE IF EXISTS public.conceptual_model_comments
    ADD CONSTRAINT conceptual_model_comments_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.conceptual_model_comments
    ADD CONSTRAINT conceptual_model_comments_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.conceptual_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_conceptual_model_comments_model_id
    ON public.conceptual_model_comments(model_id);


ALTER TABLE IF EXISTS public.conceptual_model_versions
    ADD CONSTRAINT conceptual_model_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.conceptual_model_versions
    ADD CONSTRAINT conceptual_model_versions_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.conceptual_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_conceptual_model_versions_model_id
    ON public.conceptual_model_versions(model_id);


ALTER TABLE IF EXISTS public.conceptual_models
    ADD CONSTRAINT conceptual_models_artifact_id_fkey FOREIGN KEY (artifact_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uq_conceptual_models_artifact_id
    ON public.conceptual_models(artifact_id);


ALTER TABLE IF EXISTS public.conceptual_models
    ADD CONSTRAINT conceptual_models_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.conceptual_models
    ADD CONSTRAINT conceptual_models_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_conceptual_models_project_id
    ON public.conceptual_models(project_id);


ALTER TABLE IF EXISTS public.conceptual_models
    ADD CONSTRAINT conceptual_models_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.conceptual_relations
    ADD CONSTRAINT conceptual_relations_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.conceptual_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_conceptual_relations_model_id
    ON public.conceptual_relations(model_id);


ALTER TABLE IF EXISTS public.dfd_comments
    ADD CONSTRAINT dfd_comments_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.dfd_comments
    ADD CONSTRAINT dfd_comments_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.dfd_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_dfd_comments_model
    ON public.dfd_comments(model_id);


ALTER TABLE IF EXISTS public.dfd_models
    ADD CONSTRAINT dfd_models_artifact_id_fkey FOREIGN KEY (artifact_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.dfd_models
    ADD CONSTRAINT dfd_models_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.dfd_models
    ADD CONSTRAINT dfd_models_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.dfd_models
    ADD CONSTRAINT dfd_models_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.dfd_versions
    ADD CONSTRAINT dfd_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.dfd_versions
    ADD CONSTRAINT dfd_versions_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.dfd_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_dfd_versions_model
    ON public.dfd_versions(model_id);


ALTER TABLE IF EXISTS public.gap_analysis_report_versions
    ADD CONSTRAINT gap_analysis_report_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.gap_analysis_report_versions
    ADD CONSTRAINT gap_analysis_report_versions_report_id_fkey FOREIGN KEY (report_id)
    REFERENCES public.gap_analysis_reports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.gap_analysis_reports
    ADD CONSTRAINT gap_analysis_reports_artifact_id_fkey FOREIGN KEY (artifact_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.gap_analysis_reports
    ADD CONSTRAINT gap_analysis_reports_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.gap_analysis_reports
    ADD CONSTRAINT gap_analysis_reports_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.gap_analysis_reports
    ADD CONSTRAINT gap_analysis_reports_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.gaps_crud_matrices
    ADD CONSTRAINT gaps_crud_matrices_artifact_id_fkey FOREIGN KEY (artifact_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.gaps_crud_matrices
    ADD CONSTRAINT gaps_crud_matrices_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.gaps_crud_matrices
    ADD CONSTRAINT gaps_crud_matrices_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.gaps_crud_matrices
    ADD CONSTRAINT gaps_crud_matrices_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.gaps_crud_matrix_versions
    ADD CONSTRAINT gaps_crud_matrix_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.gaps_crud_matrix_versions
    ADD CONSTRAINT gaps_crud_matrix_versions_matrix_id_fkey FOREIGN KEY (matrix_id)
    REFERENCES public.gaps_crud_matrices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.integration_quality_rules
    ADD CONSTRAINT integration_quality_rules_artifact_id_fkey FOREIGN KEY (artifact_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.integration_quality_rules
    ADD CONSTRAINT integration_quality_rules_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.integration_quality_rules
    ADD CONSTRAINT integration_quality_rules_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.integration_quality_rules
    ADD CONSTRAINT integration_quality_rules_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.integration_quality_rules_versions
    ADD CONSTRAINT integration_quality_rules_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.integration_quality_rules_versions
    ADD CONSTRAINT integration_quality_rules_versions_document_id_fkey FOREIGN KEY (document_id)
    REFERENCES public.integration_quality_rules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inventory_matrices
    ADD CONSTRAINT inventory_matrices_artifact_id_fkey FOREIGN KEY (artifact_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inventory_matrices
    ADD CONSTRAINT inventory_matrices_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.inventory_matrices
    ADD CONSTRAINT inventory_matrices_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inventory_matrices
    ADD CONSTRAINT inventory_matrices_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_matrix_versions
    ADD CONSTRAINT inventory_matrix_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_matrix_versions
    ADD CONSTRAINT inventory_matrix_versions_matrix_id_fkey FOREIGN KEY (matrix_id)
    REFERENCES public.inventory_matrices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.invitations
    ADD CONSTRAINT invitations_invited_by_user_id_fkey FOREIGN KEY (invited_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.invitations
    ADD CONSTRAINT invitations_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.invitations
    ADD CONSTRAINT invitations_target_user_id_fkey FOREIGN KEY (target_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.logical_data_model_comments
    ADD CONSTRAINT logical_data_model_comments_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.logical_data_model_comments
    ADD CONSTRAINT logical_data_model_comments_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.logical_data_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_logical_data_model_comments_model_id
    ON public.logical_data_model_comments(model_id);


ALTER TABLE IF EXISTS public.logical_data_model_versions
    ADD CONSTRAINT logical_data_model_versions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.logical_data_model_versions
    ADD CONSTRAINT logical_data_model_versions_model_id_fkey FOREIGN KEY (model_id)
    REFERENCES public.logical_data_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_logical_data_model_versions_model_id
    ON public.logical_data_model_versions(model_id);


ALTER TABLE IF EXISTS public.logical_data_models
    ADD CONSTRAINT logical_data_models_artifact_id_fkey FOREIGN KEY (artifact_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_logical_data_models_artifact_id
    ON public.logical_data_models(artifact_id);


ALTER TABLE IF EXISTS public.logical_data_models
    ADD CONSTRAINT logical_data_models_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.logical_data_models
    ADD CONSTRAINT logical_data_models_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_logical_data_models_project_id
    ON public.logical_data_models(project_id);


ALTER TABLE IF EXISTS public.logical_data_models
    ADD CONSTRAINT logical_data_models_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.maturity_answers
    ADD CONSTRAINT maturity_answers_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.maturity_questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.maturity_answers
    ADD CONSTRAINT maturity_answers_response_id_fkey FOREIGN KEY (response_id)
    REFERENCES public.maturity_responses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.maturity_questionnaires
    ADD CONSTRAINT maturity_questionnaires_closed_by_user_id_fkey FOREIGN KEY (closed_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.maturity_questionnaires
    ADD CONSTRAINT maturity_questionnaires_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.maturity_questionnaires
    ADD CONSTRAINT maturity_questionnaires_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.maturity_questions
    ADD CONSTRAINT maturity_questions_dimension_id_fkey FOREIGN KEY (dimension_id)
    REFERENCES public.maturity_dimensions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.maturity_questions
    ADD CONSTRAINT maturity_questions_questionnaire_id_fkey FOREIGN KEY (questionnaire_id)
    REFERENCES public.maturity_questionnaires (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.maturity_questions
    ADD CONSTRAINT maturity_questions_subdomain_id_fkey FOREIGN KEY (subdomain_id)
    REFERENCES public.maturity_subdomains (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.maturity_responses
    ADD CONSTRAINT maturity_responses_anulated_by_user_id_fkey FOREIGN KEY (anulated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.maturity_responses
    ADD CONSTRAINT maturity_responses_questionnaire_id_fkey FOREIGN KEY (questionnaire_id)
    REFERENCES public.maturity_questionnaires (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.maturity_responses
    ADD CONSTRAINT maturity_responses_validated_by_user_id_fkey FOREIGN KEY (validated_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.maturity_subdomains
    ADD CONSTRAINT maturity_subdomains_dimension_id_fkey FOREIGN KEY (dimension_id)
    REFERENCES public.maturity_dimensions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.project_artifact_permissions
    ADD CONSTRAINT project_artifact_permissions_artifact_id_fkey FOREIGN KEY (artifact_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.project_artifact_permissions
    ADD CONSTRAINT project_artifact_permissions_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.project_artifact_permissions
    ADD CONSTRAINT project_artifact_permissions_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.project_artifact_permissions
    ADD CONSTRAINT project_artifact_permissions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.project_artifacts
    ADD CONSTRAINT project_artifacts_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.project_artifacts
    ADD CONSTRAINT project_artifacts_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.project_memberships
    ADD CONSTRAINT project_memberships_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.project_memberships
    ADD CONSTRAINT project_memberships_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.project_memberships
    ADD CONSTRAINT project_memberships_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT projects_manager_user_id_fkey FOREIGN KEY (manager_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.raci_activities
    ADD CONSTRAINT raci_activities_matrix_id_fkey FOREIGN KEY (matrix_id)
    REFERENCES public.raci_matrices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.raci_assignments
    ADD CONSTRAINT raci_assignments_activity_id_fkey FOREIGN KEY (activity_id)
    REFERENCES public.raci_activities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.raci_assignments
    ADD CONSTRAINT raci_assignments_matrix_id_fkey FOREIGN KEY (matrix_id)
    REFERENCES public.raci_matrices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.raci_assignments
    ADD CONSTRAINT raci_assignments_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.raci_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.raci_comments
    ADD CONSTRAINT raci_comments_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.raci_comments
    ADD CONSTRAINT raci_comments_matrix_id_fkey FOREIGN KEY (matrix_id)
    REFERENCES public.raci_matrices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.raci_matrices
    ADD CONSTRAINT raci_matrices_entregable_id_fkey FOREIGN KEY (entregable_id)
    REFERENCES public.project_artifacts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.raci_matrices
    ADD CONSTRAINT raci_matrices_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.raci_roles
    ADD CONSTRAINT raci_roles_matrix_id_fkey FOREIGN KEY (matrix_id)
    REFERENCES public.raci_matrices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.raci_version_history
    ADD CONSTRAINT raci_version_history_matrix_id_fkey FOREIGN KEY (matrix_id)
    REFERENCES public.raci_matrices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id
    ON public.refresh_tokens(user_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_created_by_user_id_fkey FOREIGN KEY (created_by_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;
