"""Add RACI Matrix Models

Revision ID: 59edad17525b
Revises: 60d430ba6313
Create Date: 2026-04-06 13:03:24.978989
"""

# revision identifiers, used by Alembic.
revision = "59edad17525b"
down_revision = "60d430ba6313"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
