"""Add RACI Matrix Models

Revision ID: 60d430ba6313
Revises: 20260331_0008
Create Date: 2026-04-06 11:59:37.401849
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "60d430ba6313"
down_revision = "20260331_0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raci_matrices",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("entregable_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "ARCHIVED", name="raci_status_enum"),
            nullable=False,
        ),
        sa.Column("version_actual", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entregable_id"], ["project_artifacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raci_activities",
        sa.Column("matrix_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["matrix_id"], ["raci_matrices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raci_comments",
        sa.Column("matrix_id", sa.UUID(), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=True),
        sa.Column(
            "reference_type",
            sa.Enum("ACTIVIDAD", "ROL", "GENERAL", name="raci_comment_reference_type_enum"),
            nullable=False,
        ),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("author_nombre", sa.String(length=255), nullable=False),
        sa.Column("author_perfil", sa.String(length=255), nullable=False),
        sa.Column("contenido", sa.Text(), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["matrix_id"], ["raci_matrices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raci_roles",
        sa.Column("matrix_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("area", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["matrix_id"], ["raci_matrices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raci_version_history",
        sa.Column("matrix_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("autor", sa.String(length=255), nullable=False),
        sa.Column("descripcion_cambio", sa.Text(), nullable=False),
        sa.Column("total_actividades", sa.Integer(), nullable=False),
        sa.Column("total_roles", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["matrix_id"], ["raci_matrices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raci_assignments",
        sa.Column("matrix_id", sa.UUID(), nullable=False),
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "assignment_type",
            sa.Enum("R", "A", "C", "I", name="raci_assignment_type_enum"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["activity_id"], ["raci_activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["matrix_id"], ["raci_matrices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["raci_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", "role_id", name="uq_raci_assignment_activity_role"),
    )
    op.drop_constraint(op.f("uq_invitations_token"), "invitations", type_="unique")
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.create_index(op.f("ix_invitations_token"), "invitations", ["token"], unique=True)
    op.drop_index(op.f("ix_maturity_answers_response_id"), table_name="maturity_answers")
    op.drop_index(
        op.f("ix_maturity_questionnaires_project_id"), table_name="maturity_questionnaires"
    )
    op.drop_index(op.f("ix_maturity_questions_questionnaire_id"), table_name="maturity_questions")
    op.drop_index(op.f("ix_maturity_responses_email"), table_name="maturity_responses")
    op.drop_index(op.f("ix_maturity_responses_questionnaire_id"), table_name="maturity_responses")
    op.drop_index(
        op.f("ix_project_artifact_permissions_project_id"),
        table_name="project_artifact_permissions",
    )
    op.drop_index(op.f("ix_project_artifacts_block"), table_name="project_artifacts")
    op.drop_index(op.f("ix_project_artifacts_project_id"), table_name="project_artifacts")
    op.drop_constraint(op.f("uq_refresh_tokens_token_hash"), "refresh_tokens", type_="unique")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("uq_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_project_artifacts_project_id"), "project_artifacts", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_artifacts_block"), "project_artifacts", ["block"], unique=False
    )
    op.create_index(
        op.f("ix_project_artifact_permissions_project_id"),
        "project_artifact_permissions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maturity_responses_questionnaire_id"),
        "maturity_responses",
        ["questionnaire_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maturity_responses_email"),
        "maturity_responses",
        ["respondent_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maturity_questions_questionnaire_id"),
        "maturity_questions",
        ["questionnaire_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maturity_questionnaires_project_id"),
        "maturity_questionnaires",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maturity_answers_response_id"), "maturity_answers", ["response_id"], unique=False
    )
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.create_index(op.f("ix_invitations_token"), "invitations", ["token"], unique=False)
    op.create_unique_constraint(
        op.f("uq_invitations_token"), "invitations", ["token"], postgresql_nulls_not_distinct=False
    )
    op.drop_table("raci_assignments")
    op.drop_table("raci_version_history")
    op.drop_table("raci_roles")
    op.drop_table("raci_comments")
    op.drop_table("raci_activities")
    op.drop_table("raci_matrices")
    # ### end Alembic commands ###
