"""Add RACI Bulk support

Revision ID: ba5ecde19633
Revises: 59edad17525b
Create Date: 2026-04-06 15:41:41.772980
"""

# revision identifiers, used by Alembic.
revision = "ba5ecde19633"
down_revision = "59edad17525b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
