from __future__ import annotations

from typing import Final

DAMA_ROLE_CATALOG: Final[list[dict[str, str]]] = [
    {
        "id": "data-owner",
        "name": "Data Owner",
        "description": "Propietario de datos, responsable del negocio",
    },
    {
        "id": "data-steward",
        "name": "Data Steward",
        "description": "Custodio de datos, implementa políticas",
    },
    {
        "id": "data-custodian",
        "name": "Data Custodian",
        "description": "Guardián de datos, responsable técnico",
    },
    {
        "id": "data-analyst",
        "name": "Data Analyst",
        "description": "Analista de datos, utiliza datos",
    },
    {
        "id": "data-architect",
        "name": "Data Architect",
        "description": "Arquitecto de datos, diseña soluciones",
    },
    {
        "id": "cdo",
        "name": "Chief Data Officer",
        "description": "Liderazgo estratégico de datos",
    },
    {
        "id": "it-manager",
        "name": "IT Manager",
        "description": "Gestor de TI, infraestructura",
    },
    {
        "id": "business-manager",
        "name": "Business Manager",
        "description": "Gestor de negocio, requisitos",
    },
]


MATURITY_SCORE_CRITERIA_DEFAULT: Final[list[dict[str, int | str]]] = [
    {
        "score": 0,
        "name": "Inexistente",
        "description": "No existe evidencia de la práctica o capacidad evaluada.",
    },
    {
        "score": 1,
        "name": "Inicial",
        "description": "Existe de forma ad hoc, sin estandarización ni repetibilidad.",
    },
    {
        "score": 2,
        "name": "Básico",
        "description": "Hay prácticas parciales y algunas guías, con aplicación limitada.",
    },
    {
        "score": 3,
        "name": "Definido",
        "description": "La práctica está definida y se aplica de forma consistente en áreas clave.",
    },
    {
        "score": 4,
        "name": "Gestionado",
        "description": "Está formalizada, medida con indicadores y gobernada activamente.",
    },
    {
        "score": 5,
        "name": "Optimizado",
        "description": "Es una capacidad madura con mejora continua y evidencia transversal.",
    },
]


DAMA_DIMENSION_CATALOG: Final[list[dict[str, int | float | str]]] = [
    {
        "id": 1,
        "name": "Gobernanza de Datos",
        "description": "Estructura de roles, políticas, comités y accountability",
        "weight": 0.12,
        "display_order": 1,
    },
    {
        "id": 2,
        "name": "Arquitectura de Datos",
        "description": "Blueprint empresarial para datos, integración y almacenamiento",
        "weight": 0.09,
        "display_order": 2,
    },
    {
        "id": 3,
        "name": "Modelado y Diseño de Datos",
        "description": "Modelos conceptuales, lógicos y físicos de datos",
        "weight": 0.09,
        "display_order": 3,
    },
    {
        "id": 4,
        "name": "Almacenamiento y Operaciones",
        "description": "Gestión de datos desde creación hasta retiro",
        "weight": 0.09,
        "display_order": 4,
    },
    {
        "id": 5,
        "name": "Seguridad de Datos",
        "description": "Protección, control de accesos, privacidad y cumplimiento",
        "weight": 0.09,
        "display_order": 5,
    },
    {
        "id": 6,
        "name": "Integración e Interoperabilidad",
        "description": "Movimiento de datos entre sistemas (ETL/ELT, APIs)",
        "weight": 0.09,
        "display_order": 6,
    },
    {
        "id": 7,
        "name": "Documentos y Contenido",
        "description": "Gestión de datos no estructurados y archivos",
        "weight": 0.09,
        "display_order": 7,
    },
    {
        "id": 8,
        "name": "Datos de Referencia y Maestros",
        "description": "Master Data Management y datos compartidos",
        "weight": 0.09,
        "display_order": 8,
    },
    {
        "id": 9,
        "name": "Data Warehousing y BI",
        "description": "Almacenes de datos, reporting y analytics",
        "weight": 0.09,
        "display_order": 9,
    },
    {
        "id": 10,
        "name": "Metadatos",
        "description": "Linaje, contexto y trazabilidad de datos",
        "weight": 0.09,
        "display_order": 10,
    },
    {
        "id": 11,
        "name": "Calidad de Datos",
        "description": "Fitness-for-use, métricas y mejora continua",
        "weight": 0.09,
        "display_order": 11,
    },
]


DAMA_SUBDOMAIN_CATALOG: Final[list[dict[str, int | float | str]]] = [
    {
        "id": 1,
        "dimension_id": 1,
        "name": "Estrategia y Roadmap",
        "description": "Visión, estrategia y plan de gobernanza",
        "weight": 0.25,
        "display_order": 1,
    },
    {
        "id": 2,
        "dimension_id": 1,
        "name": "Roles y Responsabilidades",
        "description": "Data Owners, Stewards, comités",
        "weight": 0.25,
        "display_order": 2,
    },
    {
        "id": 3,
        "dimension_id": 1,
        "name": "Políticas y Estándares",
        "description": "Políticas documentadas y procedimientos",
        "weight": 0.25,
        "display_order": 3,
    },
    {
        "id": 4,
        "dimension_id": 1,
        "name": "Medición y KPIs",
        "description": "Métricas de efectividad de gobernanza",
        "weight": 0.25,
        "display_order": 4,
    },
    {
        "id": 5,
        "dimension_id": 2,
        "name": "Arquitectura Empresarial",
        "description": "Blueprint y modelos arquitectónicos",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 6,
        "dimension_id": 2,
        "name": "Estándares de Arquitectura",
        "description": "Principios y patrones arquitectónicos",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 7,
        "dimension_id": 2,
        "name": "Alineación con Negocio",
        "description": "Conexión arquitectura-estrategia",
        "weight": 0.30,
        "display_order": 3,
    },
    {
        "id": 8,
        "dimension_id": 3,
        "name": "Modelos Conceptuales",
        "description": "Entidades y relaciones de negocio",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 9,
        "dimension_id": 3,
        "name": "Modelos Lógicos",
        "description": "Estructuras normalizadas de datos",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 10,
        "dimension_id": 3,
        "name": "Modelos Físicos",
        "description": "Implementación en bases de datos",
        "weight": 0.30,
        "display_order": 3,
    },
    {
        "id": 11,
        "dimension_id": 4,
        "name": "Gestión de Almacenamiento",
        "description": "Bases de datos, performance",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 12,
        "dimension_id": 4,
        "name": "Ciclo de Vida",
        "description": "Retención, archivo, eliminación",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 13,
        "dimension_id": 4,
        "name": "Backup y Recovery",
        "description": "Continuidad y recuperación",
        "weight": 0.30,
        "display_order": 3,
    },
    {
        "id": 14,
        "dimension_id": 5,
        "name": "Control de Accesos",
        "description": "RBAC, autenticación, autorización",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 15,
        "dimension_id": 5,
        "name": "Protección y Privacidad",
        "description": "Encriptación, GDPR, LOPD",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 16,
        "dimension_id": 5,
        "name": "Auditoría y Monitoreo",
        "description": "Logs, detección de anomalías",
        "weight": 0.30,
        "display_order": 3,
    },
    {
        "id": 17,
        "dimension_id": 6,
        "name": "ETL/ELT",
        "description": "Extracción, transformación, carga",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 18,
        "dimension_id": 6,
        "name": "APIs y Servicios",
        "description": "Intercambio entre sistemas",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 19,
        "dimension_id": 6,
        "name": "Calidad de Integración",
        "description": "Consistencia en flujos",
        "weight": 0.30,
        "display_order": 3,
    },
    {
        "id": 20,
        "dimension_id": 7,
        "name": "Gestión Documental",
        "description": "Archivos, documentos, CMS",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 21,
        "dimension_id": 7,
        "name": "Clasificación de Contenido",
        "description": "Taxonomías, categorías",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 22,
        "dimension_id": 7,
        "name": "Preservación Digital",
        "description": "Conservación a largo plazo",
        "weight": 0.30,
        "display_order": 3,
    },
    {
        "id": 23,
        "dimension_id": 8,
        "name": "Master Data Management",
        "description": "Clientes, productos, entidades maestras",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 24,
        "dimension_id": 8,
        "name": "Datos de Referencia",
        "description": "Lookup tables, códigos estándar",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 25,
        "dimension_id": 8,
        "name": "Consistencia Cross-System",
        "description": "Single version of truth",
        "weight": 0.30,
        "display_order": 3,
    },
    {
        "id": 26,
        "dimension_id": 9,
        "name": "Data Warehouse",
        "description": "Almacenes de datos consolidados",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 27,
        "dimension_id": 9,
        "name": "Business Intelligence",
        "description": "Reporting, dashboards",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 28,
        "dimension_id": 9,
        "name": "Analytics Avanzado",
        "description": "Predictivo, prescriptivo, ML",
        "weight": 0.30,
        "display_order": 3,
    },
    {
        "id": 29,
        "dimension_id": 10,
        "name": "Catálogo de Metadatos",
        "description": "Inventario de activos de datos",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 30,
        "dimension_id": 10,
        "name": "Linaje de Datos",
        "description": "Trazabilidad de origen a destino",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 31,
        "dimension_id": 10,
        "name": "Glosario de Negocio",
        "description": "Diccionario de términos",
        "weight": 0.30,
        "display_order": 3,
    },
    {
        "id": 32,
        "dimension_id": 11,
        "name": "Dimensiones de Calidad",
        "description": "Accuracy, completeness, consistency",
        "weight": 0.35,
        "display_order": 1,
    },
    {
        "id": 33,
        "dimension_id": 11,
        "name": "Validación y Limpieza",
        "description": "Reglas, corrección de errores",
        "weight": 0.35,
        "display_order": 2,
    },
    {
        "id": 34,
        "dimension_id": 11,
        "name": "Monitoreo Continuo",
        "description": "Dashboards, alertas de calidad",
        "weight": 0.30,
        "display_order": 3,
    },
]


QUESTION_TEMPLATE_CATALOG: Final[list[dict[str, int | float | str | list[str]]]] = [
    {
        "template_id": 1,
        "dimension_id": 1,
        "subdomain_id": 1,
        "text": "¿Existe una estrategia formal de gobernanza de datos documentada y comunicada?",
        "applicable_roles": ["cdo", "data-owner", "business-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 2,
        "dimension_id": 1,
        "subdomain_id": 2,
        "text": "¿Existen roles definidos (Data Owner, Data Steward) con responsabilidades claras?",
        "applicable_roles": ["cdo", "data-owner", "data-steward"],
        "weight": 1.0,
    },
    {
        "template_id": 3,
        "dimension_id": 1,
        "subdomain_id": 3,
        "text": "¿Existen políticas y estándares de gestión de datos documentados?",
        "applicable_roles": ["cdo", "data-owner", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 4,
        "dimension_id": 1,
        "subdomain_id": 4,
        "text": "¿Se miden los beneficios y KPIs de la gobernanza de datos?",
        "applicable_roles": ["cdo", "data-owner", "business-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 5,
        "dimension_id": 2,
        "subdomain_id": 5,
        "text": "¿Existe una arquitectura de datos documentada con blueprint empresarial?",
        "applicable_roles": ["data-architect", "cdo", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 6,
        "dimension_id": 2,
        "subdomain_id": 6,
        "text": "¿Se definen y cumplen estándares arquitectónicos (principios, patrones)?",
        "applicable_roles": ["data-architect", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 7,
        "dimension_id": 2,
        "subdomain_id": 7,
        "text": "¿La arquitectura de datos está alineada con la estrategia del negocio?",
        "applicable_roles": ["data-architect", "cdo", "business-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 8,
        "dimension_id": 3,
        "subdomain_id": 8,
        "text": "¿Existen modelos conceptuales de datos que representen el negocio?",
        "applicable_roles": ["data-architect", "data-steward", "business-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 9,
        "dimension_id": 3,
        "subdomain_id": 9,
        "text": "¿Existen modelos lógicos normalizados de datos?",
        "applicable_roles": ["data-architect", "data-steward"],
        "weight": 1.0,
    },
    {
        "template_id": 10,
        "dimension_id": 3,
        "subdomain_id": 10,
        "text": "¿Los modelos físicos están implementados correctamente en las bases de datos?",
        "applicable_roles": ["data-architect", "data-custodian", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 11,
        "dimension_id": 4,
        "subdomain_id": 11,
        "text": "¿El almacenamiento de datos tiene performance y capacidad adecuados?",
        "applicable_roles": ["data-custodian", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 12,
        "dimension_id": 4,
        "subdomain_id": 12,
        "text": "¿Se gestiona el ciclo de vida de datos (retención, archivo, eliminación)?",
        "applicable_roles": ["data-steward", "data-custodian", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 13,
        "dimension_id": 4,
        "subdomain_id": 13,
        "text": "¿Existen procesos de backup y recovery probados?",
        "applicable_roles": ["data-custodian", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 14,
        "dimension_id": 5,
        "subdomain_id": 14,
        "text": "¿Se implementan controles de acceso basados en roles (RBAC)?",
        "applicable_roles": ["data-custodian", "it-manager", "cdo"],
        "weight": 1.0,
    },
    {
        "template_id": 15,
        "dimension_id": 5,
        "subdomain_id": 15,
        "text": "¿Se protegen datos sensibles con encriptación y se cumple privacidad (GDPR/LOPD)?",
        "applicable_roles": ["cdo", "it-manager", "data-custodian"],
        "weight": 1.0,
    },
    {
        "template_id": 16,
        "dimension_id": 5,
        "subdomain_id": 16,
        "text": "¿Se auditan y monitorean los accesos a datos?",
        "applicable_roles": ["data-custodian", "it-manager", "cdo"],
        "weight": 1.0,
    },
    {
        "template_id": 17,
        "dimension_id": 6,
        "subdomain_id": 17,
        "text": "¿Los procesos ETL/ELT están documentados y monitoreados?",
        "applicable_roles": ["data-architect", "data-custodian", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 18,
        "dimension_id": 6,
        "subdomain_id": 18,
        "text": "¿Las APIs y servicios de datos están estandarizados?",
        "applicable_roles": ["data-architect", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 19,
        "dimension_id": 6,
        "subdomain_id": 19,
        "text": "¿La integración de datos mantiene consistencia entre sistemas?",
        "applicable_roles": ["data-architect", "data-steward", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 20,
        "dimension_id": 7,
        "subdomain_id": 20,
        "text": "¿Existe un sistema de gestión documental para datos no estructurados?",
        "applicable_roles": ["data-steward", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 21,
        "dimension_id": 7,
        "subdomain_id": 21,
        "text": "¿Los documentos y contenidos están clasificados con taxonomías?",
        "applicable_roles": ["data-steward", "business-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 22,
        "dimension_id": 7,
        "subdomain_id": 22,
        "text": "¿Existe preservación digital a largo plazo para contenido crítico?",
        "applicable_roles": ["data-custodian", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 23,
        "dimension_id": 8,
        "subdomain_id": 23,
        "text": "¿Existe Master Data Management para entidades críticas (clientes, productos)?",
        "applicable_roles": ["data-steward", "data-architect", "cdo"],
        "weight": 1.0,
    },
    {
        "template_id": 24,
        "dimension_id": 8,
        "subdomain_id": 24,
        "text": "¿Los datos de referencia (lookup tables) están estandarizados?",
        "applicable_roles": ["data-steward", "data-custodian"],
        "weight": 1.0,
    },
    {
        "template_id": 25,
        "dimension_id": 8,
        "subdomain_id": 25,
        "text": "¿Existe una única versión de verdad para datos maestros cross-system?",
        "applicable_roles": ["data-steward", "data-architect", "cdo"],
        "weight": 1.0,
    },
    {
        "template_id": 26,
        "dimension_id": 9,
        "subdomain_id": 26,
        "text": "¿Existe un Data Warehouse consolidado para reporting?",
        "applicable_roles": ["data-architect", "data-analyst", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 27,
        "dimension_id": 9,
        "subdomain_id": 27,
        "text": "¿Los dashboards y reportes de BI son confiables y oportunos?",
        "applicable_roles": ["data-analyst", "business-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 28,
        "dimension_id": 9,
        "subdomain_id": 28,
        "text": "¿Se utiliza analytics avanzado (predictivo, ML) para decisiones?",
        "applicable_roles": ["data-analyst", "cdo", "business-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 29,
        "dimension_id": 10,
        "subdomain_id": 29,
        "text": "¿Existe un catálogo de metadatos con inventario de activos de datos?",
        "applicable_roles": ["data-steward", "data-architect"],
        "weight": 1.0,
    },
    {
        "template_id": 30,
        "dimension_id": 10,
        "subdomain_id": 30,
        "text": "¿El linaje de datos permite trazabilidad de origen a destino?",
        "applicable_roles": ["data-steward", "data-architect", "data-custodian"],
        "weight": 1.0,
    },
    {
        "template_id": 31,
        "dimension_id": 10,
        "subdomain_id": 31,
        "text": "¿Existe un glosario de negocio con definiciones compartidas?",
        "applicable_roles": ["data-steward", "business-manager", "cdo"],
        "weight": 1.0,
    },
    {
        "template_id": 32,
        "dimension_id": 11,
        "subdomain_id": 32,
        "text": "¿Se definen y miden dimensiones de calidad (accuracy, completeness, consistency)?",
        "applicable_roles": ["data-steward", "data-analyst", "cdo"],
        "weight": 1.0,
    },
    {
        "template_id": 33,
        "dimension_id": 11,
        "subdomain_id": 33,
        "text": "¿Existen reglas de validación y procesos de limpieza de datos?",
        "applicable_roles": ["data-steward", "data-custodian", "it-manager"],
        "weight": 1.0,
    },
    {
        "template_id": 34,
        "dimension_id": 11,
        "subdomain_id": 34,
        "text": "¿Se monitorea continuamente la calidad de datos en producción?",
        "applicable_roles": ["data-steward", "data-analyst", "it-manager"],
        "weight": 1.0,
    },
]
